# Practice 1

## Instructions

You're going to practice working in pandas. 


You'll walk through instantiating a `DataFrame`, reading data into it, looking at and examining that data, and then playing with it. 


A dataset on the [quality of red wines](https://archive.ics.uci.edu/ml/datasets/wine+quality) is used for this purpose.
It is located in the `data` folder within this directory. It's called `winequality-red.csv`. 


Typically, we use Jupyter notebooks like this for a very specific set of things - presentations and EDA. 


Today, as we'll be playing around with `pandas`, much of what we'll be doing is considered EDA. Therefore, by using a notebook, we'll get a tighter feedback loop with our work than we would trying to write a script. But, in general, **we do not use Jupyter notebooks for development**. 

Below, we've put a set of questions and then a cell for you to work on answers. However, feel free to add additional cells if you'd like. Often it will make sense to use more than one cell for your answers.

## Assignment Questions

### Part 1 - The Basics of DataFrames

Let's start off by following the general workflow that we use when moving data into a DataFrame: 

    * Importing pandas
    * Reading data into the DataFrame
    * Getting a general sense of the data

So, in terms of what you should do for this part...

1. Import pandas

In [ ]:
import os, pandas as pd

2. Read the wine data into a DataFrame.

In [54]:
df = pd.read_csv("data/winequality-red.csv", sep=";")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.40,0.70,0.00,1.90,0.08,11.00,34.00,1.00,3.51,0.56,9.40,5
1,7.80,0.88,0.00,2.60,0.10,25.00,67.00,1.00,3.20,0.68,9.80,5
2,7.80,0.76,0.04,2.30,0.09,15.00,54.00,1.00,3.26,0.65,9.80,5
3,11.20,0.28,0.56,1.90,0.07,17.00,60.00,1.00,3.16,0.58,9.80,6
4,7.40,0.70,0.00,1.90,0.08,11.00,34.00,1.00,3.51,0.56,9.40,5

3. Use the `attributes` and `methods` available on DataFrames to answer the following questions: 
    * How many rows and columns are in the DataFrame?
    * What data type is in each column?
    * Are all of the variables continuous, or are any categorical?
    * How many non-null values are in each column?
    * What are the min, mean, max, median for all numeric columns?

In [55]:
# a
print("a) columns and rows: ")
df.shape

a) columns and rows:

(1599, 12)

In [56]:
# b 
print("b) data type for each column: ")
df.info()

b) data type for each column:
<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [29]:
# c
pd.options.display.float_format = '{:.2f}'.format
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00
mean,8.32,0.53,0.27,2.54,0.09,15.87,46.47,1.00,3.31,0.66,10.42,5.64
std,1.74,0.18,0.19,1.41,0.05,10.46,32.90,0.00,0.15,0.17,1.07,0.81
min,4.60,0.12,0.00,0.90,0.01,1.00,6.00,0.99,2.74,0.33,8.40,3.00
25%,7.10,0.39,0.09,1.90,0.07,7.00,22.00,1.00,3.21,0.55,9.50,5.00
50%,7.90,0.52,0.26,2.20,0.08,14.00,38.00,1.00,3.31,0.62,10.20,6.00
75%,9.20,0.64,0.42,2.60,0.09,21.00,62.00,1.00,3.40,0.73,11.10,6.00
max,15.90,1.58,1.00,15.50,0.61,72.00,289.00,1.00,4.01,2.00,14.90,8.00

### Part 2 - Practice with Grabbing Data

Let's now get some practice with grabbing certain parts of the data. If you'd like some extra practice, try answering each of the questions in more than one way (because remember, we can often grab our data in a couple of different ways).

1. Grab the first 10 rows of the `chlorides` column.

In [57]:
df.chlorides[0:10]

0   0.08
1   0.10
2   0.09
3   0.07
4   0.08
5   0.07
6   0.07
7   0.07
8   0.07
9   0.07
Name: chlorides, dtype: float64

2. Grab the last 10 rows of the `chlorides` column.

In [58]:
df.chlorides[-10:]

1589   0.07
1590   0.08
1591   0.09
1592   0.08
1593   0.07
1594   0.09
1595   0.06
1596   0.08
1597   0.07
1598   0.07
Name: chlorides, dtype: float64

3. Grab indices 264-282 of the `chlorides` **and** `density` columns.

In [59]:
df.loc[264:282, ['chlorides', 'density']]

     chlorides  density
264       0.06     1.00
265       0.07     1.00
266       0.10     1.00
267       0.08     1.00
268       0.08     1.00
269       0.10     1.00
270       0.09     1.00
271       0.10     1.00
272       0.07     1.00
273       0.08     1.00
274       0.09     1.00
275       0.09     1.00
276       0.08     1.00
277       0.10     1.00
278       0.07     1.00
279       0.09     1.00
280       0.07     1.00
281       0.36     1.00
282       0.07     1.00

4. Grab all rows where the `chlorides` value is less than 0.10.

In [60]:
df.query('chlorides < 0.10')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.40,0.70,0.00,1.90,0.08,11.00,34.00,1.00,3.51,0.56,9.40,5
1,7.80,0.88,0.00,2.60,0.10,25.00,67.00,1.00,3.20,0.68,9.80,5
2,7.80,0.76,0.04,2.30,0.09,15.00,54.00,1.00,3.26,0.65,9.80,5
3,11.20,0.28,0.56,1.90,0.07,17.00,60.00,1.00,3.16,0.58,9.80,6
4,7.40,0.70,0.00,1.90,0.08,11.00,34.00,1.00,3.51,0.56,9.40,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.20,0.60,0.08,2.00,0.09,32.00,44.00,0.99,3.45,0.58,10.50,5
1595,5.90,0.55,0.10,2.20,0.06,39.00,51.00,1.00,3.52,0.76,11.20,6
1596,6.30,0.51,0.13,2.30,0.08,29.00,40.00,1.00,3.42,0.75,11.00,6
1597,5.90,0.65,0.12,2.00,0.07,32.00,44.00,1.00,3.57,0.71,10.20,5
1598,6.00,0.31,0.47,3.60,0.07,18.00,42.00,1.00,3.39,0.66,11.00,6

5. Now grab all the rows where the `chlorides` value is greater than the column's mean (try **not** to use a hard-coded value for the mean, but instead a method).

In [ ]:
df[(df['chlorides'])<df['chlorides'].mean()]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.40,0.70,0.00,1.90,0.08,11.00,34.00,1.00,3.51,0.56,9.40,5
3,11.20,0.28,0.56,1.90,0.07,17.00,60.00,1.00,3.16,0.58,9.80,6
4,7.40,0.70,0.00,1.90,0.08,11.00,34.00,1.00,3.51,0.56,9.40,5
5,7.40,0.66,0.00,1.80,0.07,13.00,40.00,1.00,3.51,0.56,9.40,5
6,7.90,0.60,0.06,1.60,0.07,15.00,59.00,1.00,3.30,0.46,9.40,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1593,6.80,0.62,0.08,1.90,0.07,28.00,38.00,1.00,3.42,0.82,9.50,6
1595,5.90,0.55,0.10,2.20,0.06,39.00,51.00,1.00,3.52,0.76,11.20,6
1596,6.30,0.51,0.13,2.30,0.08,29.00,40.00,1.00,3.42,0.75,11.00,6
1597,5.90,0.65,0.12,2.00,0.07,32.00,44.00,1.00,3.57,0.71,10.20,5
1598,6.00,0.31,0.47,3.60,0.07,18.00,42.00,1.00,3.39,0.66,11.00,6

6. Grab all those rows where the `pH` is greater than 3.0 and less than 3.5.

In [ ]:
pH_df = df.query('pH > 3.0 and pH < 3.5')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.80,0.88,0.00,2.60,0.10,25.00,67.00,1.00,3.20,0.68,9.80,5
2,7.80,0.76,0.04,2.30,0.09,15.00,54.00,1.00,3.26,0.65,9.80,5
3,11.20,0.28,0.56,1.90,0.07,17.00,60.00,1.00,3.16,0.58,9.80,6
6,7.90,0.60,0.06,1.60,0.07,15.00,59.00,1.00,3.30,0.46,9.40,5
7,7.30,0.65,0.00,1.20,0.07,15.00,21.00,0.99,3.39,0.47,10.00,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1592,6.30,0.51,0.13,2.30,0.08,29.00,40.00,1.00,3.42,0.75,11.00,6
1593,6.80,0.62,0.08,1.90,0.07,28.00,38.00,1.00,3.42,0.82,9.50,6
1594,6.20,0.60,0.08,2.00,0.09,32.00,44.00,0.99,3.45,0.58,10.50,5
1596,6.30,0.51,0.13,2.30,0.08,29.00,40.00,1.00,3.42,0.75,11.00,6
1598,6.00,0.31,0.47,3.60,0.07,18.00,42.00,1.00,3.39,0.66,11.00,6


7. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0.

In [80]:
pH_df.query('`residual sugar` < 2.0')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,11.20,0.28,0.56,1.90,0.07,17.00,60.00,1.00,3.16,0.58,9.80,6
6,7.90,0.60,0.06,1.60,0.07,15.00,59.00,1.00,3.30,0.46,9.40,5
7,7.30,0.65,0.00,1.20,0.07,15.00,21.00,0.99,3.39,0.47,10.00,7
10,6.70,0.58,0.08,1.80,0.10,15.00,65.00,1.00,3.28,0.54,9.20,5
13,7.80,0.61,0.29,1.60,0.11,9.00,29.00,1.00,3.26,1.56,9.10,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1569,6.20,0.51,0.14,1.90,0.06,15.00,34.00,0.99,3.48,0.57,11.50,6
1576,8.00,0.30,0.63,1.60,0.08,16.00,29.00,1.00,3.30,0.78,10.80,6
1578,6.80,0.67,0.15,1.80,0.12,13.00,20.00,1.00,3.42,0.67,11.30,6
1590,6.30,0.55,0.15,1.80,0.08,26.00,35.00,0.99,3.32,0.82,11.60,6
1593,6.80,0.62,0.08,1.90,0.07,28.00,38.00,1.00,3.42,0.82,9.50,6

### Part 3 - More Practice

Let's move on to some more complicated things. Use your knowledge of `groupby`s, `sorting` to answer the following.

1. Get the average amount of `chlorides` for each `quality` value.

In [ ]:
df.groupby('quality')['chlorides'].mean()

0.08746654158849279

 2. For observations with a `pH` greater than 3.0 and less than 4.0, find the average `alcohol` value by `pH`.

In [98]:
new_ph_df = df.query('pH > 3.0 and pH < 4')
new_ph_df.groupby('pH')['alcohol'].mean()

pH
3.01   11.32
3.02   10.20
3.03    9.63
3.04    9.74
3.05   10.05
        ...
3.74   11.50
3.75   10.50
3.78   12.40
3.85   12.90
3.90   12.95
Name: alcohol, Length: 75, dtype: float64

3. For observations with an `alcohol` value between 9.25 and 9.5, find the highest amount of `residual sugar`.

In [107]:
df.query('alcohol > 9.25 and alcohol < 9.5')['residual sugar'].max()

np.float64(10.7)

4. Create a new column, called `total_acidity`, that is the sum of `fixed acidity` and `volatile acidity`.

In [114]:
df.eval('total_acidity = `fixed acidity` + `volatile acidity`', inplace= True)
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'total_acidity'],
      dtype='str')

5. Find the average `total_acidity` for each of the `quality` values.

In [115]:
df.groupby('quality')['total_acidity'].mean()

quality
3   9.24
4   8.47
5   8.74
6   8.84
7   9.28
8   8.99
Name: total_acidity, dtype: float64

6. Find the top 5 `density` values.

In [127]:
df.sort_values('density', ascending=False).head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,total_acidity
1435,10.20,0.54,0.37,15.40,0.21,55.00,95.00,1.00,3.18,0.77,9.00,6,10.74
1434,10.20,0.54,0.37,15.40,0.21,55.00,95.00,1.00,3.18,0.77,9.00,6,10.74
442,15.60,0.69,0.76,3.70,0.10,6.00,43.00,1.00,2.95,0.68,11.20,7,16.29
554,15.50,0.65,0.49,4.20,0.10,10.00,23.00,1.00,2.92,0.74,11.10,5,16.14
557,15.60,0.65,0.49,4.20,0.10,10.00,23.00,1.00,2.92,0.74,11.10,5,16.25

7. Find the 10 lowest `sulphates` values.

In [130]:
df.sort_values('sulphates', ascending=True).head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,total_acidity
170,7.90,0.89,0.03,1.80,0.06,4.00,8.00,1.00,3.36,0.33,9.10,4,8.79
1369,6.60,0.61,0.00,1.60,0.07,4.00,8.00,0.99,3.33,0.37,10.40,4,7.21
1287,8.00,0.60,0.08,2.60,0.06,3.00,7.00,0.99,3.22,0.37,13.00,5,8.60
65,7.20,0.72,0.05,4.65,0.09,4.00,11.00,1.00,3.41,0.39,10.90,5,7.92
1348,7.20,0.66,0.03,1.80,0.08,7.00,12.00,1.00,3.34,0.39,9.50,5,7.86
837,6.70,0.28,0.28,2.40,0.01,36.00,100.00,0.99,3.26,0.39,11.70,7,6.98
836,6.70,0.28,0.28,2.40,0.01,36.00,100.00,0.99,3.26,0.39,11.70,7,6.98
64,7.20,0.72,0.05,4.65,0.09,4.00,11.00,1.00,3.41,0.39,10.90,5,7.92
1347,7.20,0.66,0.03,1.80,0.08,7.00,12.00,1.00,3.34,0.39,9.50,5,7.86
1299,7.60,1.58,0.00,2.10,0.14,5.00,9.00,0.99,3.50,0.40,10.90,3,9.18